services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_kadis_2
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./prisma/migrations/20260507085813_init/dump-db_kadis_2-202605112306-2.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: mysql://admin:admin_password@db:3306/db_kadis_2
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin_password
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
